### PR TITLE
Updated search, recipe and comment endpoints. 

### PR DESCRIPTION
**Pull request by tinnytintin10**
I updated the milestone-2 document with the API endpoint(s) information. I now included the HTTP method each endpoint uses in the heading of each endpoint description. I also updated all my js files to typescript and then compiled them to js. I have tested all the endpoints with postman and they work.

### CODE REVIEW

**Comment by syoung20** [comment]
Just have some questions/suggestions - mostly regarding parameters in the requests and what data is included in responses.


For documentation of recipes/add, maybe list the parameters that will be be submitted with the form? Also you have in the documentation that you will return a status code in response, but the code only responds by rendering a file.

Recipe/read should return list of ingredients instead of a string probably - as it currently is in your ts/js code. Does description mean the instructions? 
Also, there’s a lot more data that should be returned in addition to the data you have listed, including author, prep time, cook time, #servings, and tags. That should probably be reflected in recipe/edit as well.

All of recipes/edit, recipes/del, recipes/addgroceries, and recipes/saverecipe, comments/add, comments/del, and comments/edit should probably have userID as a parameter. Additionally, recipes/addgroceries should probably have recipeID as parameter, and comments/edit include commentID as parameter.

We should either have a recipes/comments/read endpoint (which would be requested after a request to recipes/read), or have the recipes/read endpoint also respond with comment data. Right now there is no way to view any comment data.

For searching, the results data returned should probably match what Nick had (I think included image and maybe other things). And also a recipe ID.

Did you mean to have a separate comments/comments.ts file? Just because you already have those endpoints in recipes.ts.

Also not a huge deal, but you spelled description and ingredients wrong in a few places, haha.

**Comment by tinnytintin10** [comment]
> For documentation of recipes/add, maybe list the parameters that will be submitted with the form? Also, you have in the documentation that you will return a status code in response, but the code only responds by rendering a file.

Once we start building the form and get an idea of everything that will be included, I'll update the parameter list. You're right about the response code, I'll update it accordingly.

**Comment by tinnytintin10** [comment]
> Recipe/read should return list of ingredients instead of a string probably - as it currently is in your ts/js code. Does description mean the instructions?

I have made it a list. And yes it does, I have been pretty loose with these fields because I didn't want to put that much time into them as they will probably change a whole lot the next couple of days. So these parameters are pretty vague right now but as our frontend and gets fully functional and we know exactly how our data will be structured, these parameters will get handled properly. 
 
> Also, there’s a lot more data that should be returned in addition to the data you have listed, including author, prep time, cook time, #servings, and tags. That should probably be reflected in recipe/edit as well.

yes, once we build out the form and agree on exactly what information a recipe object will hold I will update the parameters. all across the board. I will update the documentation accordingly too, but for milestone 2 we should be okay.

**Comment by tinnytintin10** [comment]
> All of recipes/edit, recipes/del, recipes/addgroceries, and recipes/saverecipe, comments/add, comments/del, and comments/edit should probably have userID as a parameter. Additionally, recipes/addgroceries should probably have recipeID as parameter, and comments/edit include commentID as parameter.

I am not sure about this as we don't know how authentication is handled and therefore we don't know how we will be identity checking. Maybe it will be with the userID parameter but maybe not... either way I want to implement that later on when we know for sure instead doing it now completely in the dark.

**Comment by tinnytintin10** [comment]
> We should either have a recipes/comments/read endpoint (which would be requested after a request to recipes/read), or have the recipes/read endpoint also respond with comment data. Right now there is no way to view any comment data.

this is true, I completely missed it. I will add this to the recipes/read route as it wouldn't make sense to make two separate requests for the same page.

**Pull request merged**
